SAMMYTECHPLAYGROUND_VERSION=1.0
SAMMYTECHPLAYGROUND_SITE=package/sammytechplayground/src
SAMMYTECHPLAYGROUND_SITE_METHOD=local
SAMMYTECHPLAYGROUND_DEPENDENCIES=json-c libyaml mosquitto

define SAMMYTECHPLAYGROUND_BUILD_CMDS
	$(MAKE) CC="$(TARGET_CC)" LD="$(TARGET_LD)" AR="$(TARGET_AR)" -C $(@D)
endef

define SAMMYTECHPLAYGROUND_INSTALL_TARGET_CMDS
endef

$(eval $(generic-package))
